== Postdeployment steps

=== Set AWS Lake Formation permissions

Follow these steps to enable AWS Lake Formation to control your AWS Glue Data Catalog resources and to give your AWS Identity and Access Management (IAM) role permission to access the tables in the Data Catalog.

. Sign in to the AWS Management Console, and open the AWS Lake Formation console.

. Grant Lake Formation administrative permissions to your IAM role.
.. In the navigation pane, under *Permissions*, choose *Administrative roles and tasks*
.. Click on *Choose administrators* and enter your current IAM role

. Enable Lake Formation to control your Data Catalog resources.
.. In the navigation pane, under *Data catalog*, choose *Settings*.
.. Clear both check boxes and choose *Save*.

The following steps can be repeated for any users you wish to grant database access to.

. Give your IAM role permission to access the tables in the Data Catalog.
.. In the navigation pane, under *Permissions*, choose *Data Lake Permissions*.
.. Choose *Grant* in the upper right, and do the following:
* For *IAM users and roles*, enter enter your current IAM role.
* For *LF-Tags or catalog resources*, choose *Named data catalog resources*.
* For *Databases*, choose your database: `aws_datalake_<environment>_<team>_<name>_db"` (default `aws_datalake_dev_demoteam_amcdataset_db`).
* For *Tables*, choose *All Tables*.
* Keep *Data Filters - Optional* empty.
* For *Table Permissions*, choose *Super*.
.. Choose *Grant* at the bottom.

=== View the Operational Guide

After completing the steps above, check out the Operational Guide for help getting started using the solution {#TODO INSERT LINK TO OPERATIONAL GUIDE}.